name: Integration Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Self test
        id: selftest

        uses: Atlendis/eth-brownie@master

      - name: Check brownie version
        run: |
          brownie version
